name: "Basic Terraform OIDC and Entra Auth"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "aks_byocni_cilium"
    env:
      TERRAFORM_LOG: "WARN"
      ARM_CLIENT_ID: $
      ARM_SUBSCRIPTION_ID: $
      ARM_TENANT_ID: $
      BACKEND_RG: $
      BACKEND_SG: $
      BACKEND_CONTAINER: $
      BACKEND_KEY: $

    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4

      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Version"
        id: version
        run: terraform --version

      - name: "Terraform Init"
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=$BACKEND_RG" \
            -backend-config="storage_account_name=$BACKEND_SG" \
            -backend-config="container_name=$BACKEND_CONTAINER" \
            -backend-config="key=$BACKEND_KEY" \

      - name: "Terraform Plan"
        id: plan
        run: |
          terraform plan -out=terraform.tfplan

      - name: "Upload Terraform Plan to Working Directory"
        uses: actions/upload-artifact@v4
        with:
          name: terraformPlan
          path: "terraform.tfplan"

      - name: "Terraform Apply using Plan File"
        id: apply
        run: terraform apply terraform.tfplan
