name: "terraform-trivy-multiple-scan-with-gitleaks"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  gitleaks:
    name: "Gitleaks Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.1_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        id: gitleaks
        run: |
          gitleaks detect --source . -v | tee gitleaks_output.txt
        continue-on-error: true

      - name: Add Gitleaks results to summary
        if: always()
        run: |
          echo "## Gitleaks Scan Results" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ steps.gitleaks.outcome }}" == "failure" ]]; then
            echo "⚠️ Gitleaks found potential secrets in your code." >> $GITHUB_STEP_SUMMARY
            echo "### Detected Leaks:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat gitleaks_output.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No leaks detected by Gitleaks." >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Check for leaks
        if: steps.gitleaks.outcome == 'failure'
        run: exit 1

  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    needs: gitleaks
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TERRAFORM_DIR }}
    env:
      TERRAFORM_DIR: trivy-scan 
      TERRAFORM_LOG: "WARN"
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BACKEND_RESOURCE_GROUP: ${{ secrets.BACKEND_RESOURCE_GROUP }}
      BACKEND_STORAGE_ACCOUNT: ${{ secrets.BACKEND_STORAGE_ACCOUNT }}
      BACKEND_CONTAINER_NAME: ${{ secrets.BACKEND_CONTAINER_NAME }}
      BACKEND_KEY: ${{ secrets.BACKEND_KEY }}

    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4